name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Congratulations on your first issue to NearBeach. Thank you for making NearBeach better for the community"
        pr-message: "WHOOP WHOOO - A pull request for NearBeach. You are awesome"
